sudo: required
services:
  - docker

before_install:
  - docker build -t timmcnamaradev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run timmcnamaradev/react-test npm test -- --coverage

after_success:
  - docker build -t timmcnamaradev/multi-nginx:latest ./nginx
  - docker build -t timmcnamaradev/multi-server:latest ./server
  - docker build -t timmcnamaradev/multi-client:latest ./client
  - docker build -t timmcnamaradev/multi-worker:latest ./worker

  # Log into docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker-hub
  - docker push timmcnamaradev/multi-nginx:latest
  - docker push timmcnamaradev/multi-server:latest
  - docker push timmcnamaradev/multi-client:latest
  - docker push timmcnamaradev/multi-worker:latest

deploy:
  provider: elasticbeanstalk
  region: southeast-2
  app: multi-docker
  env: MultiDocker-env
  bucket-name: elasticbeanstalk-us-east-1-778767175131
  bucket-path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
